In [1]:
#good 
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import warnings
import os.path
import seaborn as sns

from matplotlib.pyplot import cm

warnings.filterwarnings('ignore')
warnings.filterwarnings('ignore')
pd.options.mode.chained_assignment = None
from scipy.optimize import curve_fit

In [2]:
#os.chdir('/Users/jennagreene/Library/Mobile Documents/com~apple~CloudDocs/Documents/GitHub/country-tech-growth')
os.chdir('/Users/jennagreene/Documents/GitHub/country-tech-growth')

In [8]:
country_vars = pd.read_csv("all_gov_combined_Updated.csv", index_col = False)


tech_vars = pd.read_csv("combined_tech_characteristics_Updated.csv", index_col = False)
timeseries = pd.read_csv('all_tech_clean_cumulative_Updated.csv', index_col = False)




tech_vars
country_vars

,Variable,technology,country,Country Name,Metric,Exponential Fit,exponential goodness,Logistic Fit,Logistic Saturation,Logistic Inflection Year,...,easier_scitech_Average,gdppc_Average,Capacity_Average,gee_Average,regime_Mode,IncomeGroup_Mode,WTO_Mode,OECD_Mode,dem,Log_GDPavg
0,Sugar Output_Annual Production_JM,Sugar Output,JAM,Jamaica,Annual Production,0.010363684595067636,4.878853e-01,0.2011690296389622,2.892051e+02,1939.349936943414,...,NaN,1018.916667,NaN,NaN,NaN,NaN,NaN,NaN,NaN,6.926495
1,Sugar Output_Annual Production_BB,Sugar Output,BRB,Barbados,Annual Production,err,NaN,0.03645104431526183,1.046861e+02,1888.3465511854533,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Sugar Output_Annual Production_CU,Sugar Output,CUB,Cuba,Annual Production,0.01993314084039363,-6.980338e+04,0.06952940883245123,5.281604e+03,1916.230673671623,...,NaN,1669.545455,NaN,NaN,NaN,NaN,NaN,NaN,Not Democracy,7.420307
3,Beer_Annual Production_GB,Beer Production,GBR,UK,Annual Production,err,NaN,0.2918319500873288,5.051412e+04,1875.207966104338,...,NaN,3663.873016,NaN,NaN,NaN,NaN,NaN,NaN,Not Democracy,8.206276
4,Sugar Output_Annual Production_MU,Sugar Output,MUS,Mauritius,Annual Production,0.03437627253695661,-5.801086e+29,0.03485197946836343,6.843437e+02,1934.8358453742271,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6027,Crop Harvester_Total Number_UZ,Crop Harvester,UZB,Uzbekistan,Total Number,-0.014836821402724736,2.131628e-14,err,9.184060e+06,err,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6028,Television_Total Number_BA,Television,BIH,Bosnia-Herzegovina,Total Number,err,NaN,0.028280425189326018,4.993456e+09,2329.81726869451,...,NaN,7424.273221,-0.253245,-0.757401,3.0,UM,NaN,NaN,NaN,8.912510
6029,BCG Vaccine_Share of Population_AT,BCG Vaccine,AUT,Austria,Share of Population,0.0,1.000000e+00,err,4.993456e+09,err,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6030,MCV2 Vaccine_Share of Population_DJ,MCV2 Vaccine,DJI,Djibouti,Share of Population,-0.059502026261818025,0.000000e+00,err,4.993456e+09,err,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6031,Crop Harvester_Total Number_UA,Crop Harvester,UKR,Ukraine,Total Number,-0.051579743575410175,1.110223e-16,err,4.993456e+09,err,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [9]:
tech_vars['technology'].unique()

array(['Acrylic Fiber', 'Acrylonitrile', 'Air-Source Heat Pumps',
       'All Biofuels', 'Amazon Prime Users', 'Ammonia Synthesis',
       'Aniline', 'Aquaculture Production', 'Automatic Transmission',
       'BCG Vaccine', 'Beer Production', 'Benzene', 'Bicycles', 'Biogas',
       'BisphenolA', 'Cable TV', 'Cadmium Refining', 'Canals',
       'Cane Sugar', 'Caprolactam', 'Capture Fisheries',
       'Carbon Capture and Sequestration', 'Caustic Soda', 'Cellphones',
       'Cement', 'Central Heating', 'Coal Power', 'Coal Production',
       'Cobalt', 'Compact Fluorescent Light Bulbs', 'Computing Growth',
       'Copper|Mining', 'Copper|Refining', 'Crop Harvester', 'Crude Oil',
       'Cyclohexane', 'Desalination Capacity', 'Dishwashers',
       'Disk Brakes', 'DTP1 Vaccine', 'DTP3 Vaccine', 'Ebook Reader',
       'Electric Bicycles', 'Electric Range', 'Electricity',
       'Electronic Ignition', 'Ethanol', 'Ethanolamine', 'Ethylene',
       'Ethylene Glycol', 'Flow Battery Storage',
       'Fluid Catalytic Cracking Refineries', 'Flush Toilet',
       'Flywheel Battery Storage', 'Formaldehyde', 'Freezer',
       'Geothermal Energy', 'Gold', 'Graphite',
       'Heat Thermal Battery Storage', 'HEPB3 Vaccine', 'HEPBB Vaccine',
       'Herbicide-Tolerant Corn', 'Herbicide-Tolerant Cotton',
       'Herbicide-Tolerant Soybeans', 'HIB3 Vaccine',
       'High-Density Polyethylene', 'High Speed Rail',
       'Home Air Conditioning', 'Home Computers',
       'Household Internet Access',
       'Households With Only Mobile Phones (No Landlines)',
       'Hydrochloric Acid', 'Hydroelectricity', 'Hydrofluoric Acid',
       'Insect-Resistant Corn', 'Insect-Resistant Cotton',
       'Internet Backbone Bandwidth', 'Internet Traffic', 'IPV1 Vaccine',
       'Iron', 'Iron Ore', 'Jet Aircraft', 'Latent Heat Storage',
       'Laundry Dryers', 'Lead', 'Lead-Acid Battery Storage',
       'Liquefied Natural Gas', 'Liquid Biofuels',
       'Lithium Mine Production', 'Lithium-Ion Battery Storage',
       'Low-Density Polyethylene', 'Magnetic Data Storage',
       'Maleic Anhydride', 'Marine Energy', 'MCV1 Vaccine',
       'MCV2 Vaccine', 'Methanol', 'Microcomputers',
       'Microprocessor Clock Speed', 'Microwaves', 'Milk Production',
       'Motor Gasoline', 'Motorcycles', 'Natural Gas Pipelines',
       'Natural Gas Power', 'Natural Gas Production', 'Neoprene Rubber',
       'Nickel Production', 'Nitric Acid', 'Nitrogen Fertilizer',
       'Nox Pollution Controls (Boilers)', 'Nuclear Energy',
       'Nuclear Weapons', 'Offshore Wind Energy', 'Oil Pipelines',
       'Oil Production', 'Oil Refining Capacity', 'Onshore Wind Energy',
       'Paraxylene', 'PCV3 Vaccine', 'Pentaerythritol', 'Phenol',
       'Phosphate Fertilizer', 'Phthalic Anhydride', 'Podcasting',
       'POL3 Vaccine', 'Polyester Fiber', 'Polystyrene',
       'Polyvinylchloride', 'Postal Traffic', 'Potash Fertilizer',
       'Power Steering', 'Primary Aluminum Production',
       'Primary Bauxite Production', 'Primary Copper',
       'Primary Magnesium', 'Processor Performance', 'Public Roads',
       'Pumped Hydro Storage', 'Radial Tires', 'Radio', 'Railroad',
       'Random Access Memory', 'Rare Earth Mine Production',
       'Raw Steel Production', 'RCV1 Vaccine',
       'Real-Time Gross Settlement Adoption', 'Refrigerators',
       'Renewable Power', 'ROTAC Vaccine', 'Running Water',
       'Salt Production', 'Sand and Gravel|Construction',
       'Sand and Gravel|Industrial', 'Sensible Heat Storage',
       'Shale Production', 'Shotgun Sanger DNA Sequencing', 'Silver',
       'Smartphone Usage', 'Social Media Usage', 'Sodium',
       'Sodium Chlorate', 'Sodium-Based Battery Storage',
       'Solar Photovoltaic', 'Solar Thermal Energy', 'Solid Biofuels',
       'Objects Launched Into Space', 'Steamships', 'Stove', 'Styrene',
       'Submarine Cables', 'Sulphuric Acid', 'Synthetic Filaments',
       'Tablet', 'Telegraph Traffic', 'Telephones', 'Television', 'Tin',
       'Titanium Sponge', 'Transistors per Microprocessor', 'Urea',
       'Vacuums', 'Videocassette Recorder', 'Vinyl Acetate',
       'Vinyl Chloride', 'Washing Machines', 'Water Heater',
       'Wet Flue Gas Desulfurization Systems', 'YFV Vaccine', 'Zinc'],
      dtype=object)

In [10]:
all_growth_merge = pd.merge(country_vars, tech_vars, on='technology', how='inner')

all_growth_merge.columns

Index(['Variable', 'technology', 'country', 'Country Name', 'Metric',
       'Exponential Fit', 'exponential goodness', 'Logistic Fit',
       'Logistic Saturation', 'Logistic Inflection Year', 'logistic goodness',
       'Gompertz Fit', 'gompertz goodness', 'Delta T', 'Vintage',
       'Number of Points', 'lendingrate_Average', 'rdspending_Average',
       'goodsservices_Average', 'oresmetals_Average', 'fdi_Average',
       'hightech_Average', 'polity_Average', 'direction_scitech_Average',
       'easier_scitech_Average', 'gdppc_Average', 'Capacity_Average',
       'gee_Average', 'regime_Mode', 'IncomeGroup_Mode', 'WTO_Mode',
       'OECD_Mode', 'dem', 'Log_GDPavg', 'Material Use Numerical',
       'Final Material Use', 'Year of Invention',
       'Year of First Embodiment of Tech', 'FirstCommercialYr',
       'Need for Customization', 'Complexity', 'Type of Adopter',
       'Granularity Numerical', 'Granularity', 'Average lifetime',
       'Technology Lifetime', 'Strict replacement', 'Broad replacement',
       'Feedstock', 'Category Type', 'Patent Category Name'],
      dtype='object')

In [21]:
all_growth_merge = all_growth_merge.rename(columns={'Variable': 'ID'})

In [20]:
all_growth_merge

,Variable,technology,country,Country Name,Metric,Exponential Fit,exponential goodness,Logistic Fit,Logistic Saturation,Logistic Inflection Year,...,Type of Adopter,Granularity Numerical,Granularity,Average lifetime,Technology Lifetime,Strict replacement,Broad replacement,Feedstock,Category Type,Patent Category Name
0,Beer_Annual Production_GB,Beer Production,GBR,UK,Annual Production,err,NaN,0.2918319500873288,5.051412e+04,1875.207966104338,...,Individuals [2],Expensive,Low,14.0,Years,No,No,No,Food and Health,Human Necessities
1,Railroad_Total Length_FI,Railroad,FIN,Finland,Total Length,0.028805244187556877,-1.498811e+22,0.06303629879868425,5.750939e+03,1904.2977491846548,...,Firms [1],29520,Low,55.0,Decades,No,Yes,Yes,Infrastructure,Fixed Constructions
2,Railroad_Total Length_FR,Railroad,FRA,France,Total Length,0.043827731269681314,-5.492536e+46,0.1069184437466387,3.850702e+04,1873.2535682095772,...,Firms [1],29520,Low,55.0,Decades,No,Yes,Yes,Infrastructure,Fixed Constructions
3,Railroad_Total Length_NO,Railroad,NOR,Norway,Total Length,0.0279283386346299,-3.456598e+15,0.0681333715758784,4.314916e+03,1899.8520710530436,...,Firms [1],29520,Low,55.0,Decades,No,Yes,Yes,Infrastructure,Fixed Constructions
4,Railroad_Total Length_DK,Railroad,DNK,Denmark,Total Length,0.028239483906676844,-2.667194e+17,0.1050770978243002,4.569571e+03,1886.324025572369,...,Firms [1],29520,Low,55.0,Decades,No,Yes,Yes,Infrastructure,Fixed Constructions
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5594,Crop Harvester_Total Number_UZ,Crop Harvester,UZB,Uzbekistan,Total Number,-0.014836821402724736,2.131628e-14,err,9.184060e+06,err,...,Both [3],114500,Medium,NaN,Years,No,Yes,Yes,Food and Health,Human Necessities
5595,Television_Total Number_BA,Television,BIH,Bosnia-Herzegovina,Total Number,err,NaN,0.028280425189326018,4.993456e+09,2329.81726869451,...,Individuals [2],1232.262883,Medium,15.0,Years,No,Yes,No,Appliances,Human Necessities
5596,BCG Vaccine_Share of Population_AT,BCG Vaccine,AUT,Austria,Share of Population,0.0,1.000000e+00,err,4.993456e+09,err,...,Individuals [2],2.5,High,2.0,Months,No,No,No,Food and Health,Human Necessities
5597,MCV2 Vaccine_Share of Population_DJ,MCV2 Vaccine,DJI,Djibouti,Share of Population,-0.059502026261818025,0.000000e+00,err,4.993456e+09,err,...,Individuals [2],24.9625,High,2.0,Months,No,No,No,Food and Health,Human Necessities
5598,Crop Harvester_Total Number_UA,Crop Harvester,UKR,Ukraine,Total Number,-0.051579743575410175,1.110223e-16,err,4.993456e+09,err,...,Both [3],114500,Medium,NaN,Years,No,Yes,Yes,Food and Health,Human Necessities

In [30]:
# Count number of points. 
# all_growth_merge has the characteristics
# Original growth is in time_series
characteristics_timeseries_merge =all_growth_merge.merge( timeseries, on='ID', how='inner')

In [39]:
characteristics_timeseries_merge_sum

,1702,1703,1704,1705,1706,1707,1708,1709,1710,1711,...,2016,2017,2018,2019,2020,2021,2022,2023,2024,2025
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5594,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5595,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5596,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5597,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.81,0.81,0.81,0.81,0.6,0.48,NaN,NaN,NaN,NaN
5598,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [38]:
characteristics_timeseries_merge
characteristics_timeseries_merge_sum = characteristics_timeseries_merge.iloc[:,60:]
# Count the number of non-zero and non-NaN values in the entire DataFrame
non_zero_non_nan_counts = ((characteristics_timeseries_merge_sum != 0) & (~characteristics_timeseries_merge_sum.isna())).sum().sum()

# Print the result
print("Total non-zero and non-NaN values in the DataFrame:", non_zero_non_nan_counts)

Total non-zero and non-NaN values in the DataFrame: 204784

In [13]:
all_growth_merge.to_csv('all_growth_merge_Updated.csv', index = False)

In [14]:

# Define the new folder path
new_folder = "summary_tables"

# Change the current working directory to the new folder
os.chdir(new_folder)


tech_char = pd.read_csv("sorted_tech_characteristics_Updated.csv", index_col = False)
tech_char = tech_char.rename(columns={"Technology Name": "technology", "Country Name": "country"})
tech_char

,Unnamed: 0,technology,country,num values,num years,First Year of Data,First Value,Last Year of Data,Last Value
0,5675,Air-Source Heat Pumps,NOR,13,13,2011,86950.0,2023,151260.0
1,5545,Air-Source Heat Pumps,POL,14,14,2010,3560.0,2023,116330.0
2,5744,Air-Source Heat Pumps,CZE,12,12,2010,4199.0,2021,28380.0
3,5028,Air-Source Heat Pumps,USA,20,20,2003,1626365.0,2022,4334479.0
4,5661,Air-Source Heat Pumps,CHE,13,13,2010,20740.0,2022,51750.0
...,...,...,...,...,...,...,...,...,...
6027,1060,Zinc,ARG,62,62,1942,0.4,2003,42.0
6028,340,Zinc,AUS,109,109,1889,0.2,2003,570.0
6029,2968,Zinc,IND,37,37,1967,3.0,2003,278.0
6030,3616,Zinc,DZA,30,30,1974,4.0,2003,25.0
6031,667,Zinc,PER,64,64,1940,0.2,2003,202.0